package com.example.indiga.enums;

public enum State {

    FREE,

    FAQ_WAIT_QUESTION,

    REGISTER_WAIT_FIO, REGISTER_WAIT_COMPANY, REGISTER_WAIT_PHONE,

    CALENDAR_WAIT_CHOOSE_DATE, CALENDAR_WAIT_TIME,

    DISCOUNT_SETUP_WAIT_BEGIN, DISCOUNT_SETUP_WAIT_MESSAGE,

    ADMIN_WAIT_CONTACT_MESSAGE,

    SHEDULED_WAIT_COMMAND

}
